### ISSUE TITLE
now the probleme is so serious because of big data

### ISSUE THREAD

**Issue by amine8ghandi8amine** [atayahmet/laravel-nestable#26]
![nestable services](https://user-images.githubusercontent.com/18240387/28224250-5324db8a-68c6-11e7-932a-de3e5be33cc7.png)

**Comment by amine8ghandi8amine** [comment]
give me you facebook to talk to you aboute this feature

**Comment by atayahmet** [comment]
What is the total number of your categories? This problem seems too much category number. 

Please check: [https://stackoverflow.com/questions/5164930/fatal-error-maximum-execution-time-of-30-seconds-exceeded](https://stackoverflow.com/questions/5164930/fatal-error-maximum-execution-time-of-30-seconds-exceeded)
